spring:
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:5432/avengers_db
    username: postgres
    password: password
  jpa:
    show-sql: true
server:
  error:
    include-stacktrace: on_param